
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.PitState")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.Sectors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.TractionControlLevel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.Tracks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.ClassicDrivers")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.ClassicTeams")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.ModernDrivers")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.ModernTeams")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.Eras")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.Flags")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.FuelMixes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.PitStates")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "A bug is causing these to be recognised as constants, meaning an error which shouldn't be appearing appears", Scope = "type", Target = "~T:TelemetryViewer.Server.Helpers.Enums.SessionTypes")]
